[build]
target-dir = "${CMAKE_CURRENT_BINARY_DIR}/target"

[env]
CC_${LLVM_TRIPLE} = "${CMAKE_C_COMPILER}"
CXX_${LLVM_TRIPLE} = "${CMAKE_CXX_COMPILER}"
CFLAGS_${LLVM_TRIPLE} = "${CMAKE_C_FLAGS}"
CXXFLAGS_${LLVM_TRIPLE} = "${CMAKE_CXX_FLAGS}"

LLDB_INCLUDE = "${CMAKE_BINARY_DIR}/lldb/include"
LLDB_LINK_LIB = "liblldb"
LLDB_LINK_SEARCH = "${CMAKE_BINARY_DIR}/lldb/lib"
LLDB_DYLIB_SEARCH = "${CMAKE_BINARY_DIR}/lldb/bin"
LLDB_DYLIB = "${CMAKE_BINARY_DIR}/lldb/bin/liblldb${DylibSuffix}"
ADAPTER_SOURCE_DIR = "${CMAKE_SOURCE_DIR}/adapter"
