[package]
name = "codelldb"
version = "0.1.0"
authors = ["Vadim Chugunov <vadimcn@gmail.com>"]
edition = "2018"

[dependencies]
raw_debug_protocol = { package = "debug-protocol", path = "deps/debug-protocol" }
lldb = { path = "deps/lldb" }
serde = "1.0.66"
serde_derive = "1.0.66"
serde_json = "1.0.20"
failure = "0.1.2"
failure_derive = "0.1.2"
log = "0.4.2"
env_logger = "0.5.12"
tokio = "0.1.14"
futures = "0.1.20"
bytes = "0.4.11"
regex = "1.0.2"
globset = "0.4.0"
superslice = "0.1.0"
lazy_static = "1.2.0"
clap = "2.32.0"

[lib]
crate-type = ["cdylib"]
