[package]
name = "debug-protocol"
version = "0.1.0"
authors = ["Vadim Chugunov <vadimcn@gmail.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
schemafy = "0.5.0"

