[package]
name = "lldb"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lldb.rs"

[dependencies]
cpp = "0.5"
bitflags = "1.0"
lazy_static = "1.3.0"

[build-dependencies]
cpp_build = "0.5"

[features]
weak-linkage = [] # weak-link to libpython
no-link-cpp-stdlib = [] # don't link to C++ libstd
